# Generated by Django 3.1 on 2020-09-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traj_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLBenchTrajectory',
            fields=[
                ('trajectory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='traj_db.trajectory')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('traj_db.trajectory',),
        ),
    ]
