# Generated by Django 3.1 on 2020-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traj_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajectory',
            name='episode_type',
            field=models.CharField(choices=[('EPISODE_ROBOT_IMITATED', 'Script Generated by Imitation of Play-Data'), ('EPISODE_ROBOT_PLAY', 'Human Demonstration: Play-Data'), ('EPISODE_ROBOT_EXPERT', 'Human Demonstration: Expert, Task Specific'), ('EPISODE_ROBOT_POLICY', 'Collected by Task Specific Policy'), ('EPISODE_ROBOT_EXPLORED', 'Generated by (Random) Exploration'), ('EPISODE_ROBOT_RANDOM', 'For Testing')], default='EPISODE_ROBOT_PLAY', max_length=30),
        ),
    ]
