# Generated by Django 3.1 on 2020-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight_instruction', '0002_auto_20200922_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction_count',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
