# Generated by Django 3.1 on 2020-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindsight_instruction', '0004_remove_instruction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='instruction_path',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
