# Generated by Django 3.1 on 2020-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traj_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajectory',
            name='traj_count',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
